In [27]:
import pandas as pd
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import csv
import dash

In [28]:
data = pd.read_csv("region_year_imigration.csv")

In [29]:
indices_to_keep = list(range(4, 14)) + list(range(16, 21)) + list(range(23, 32)) + list(range(33, 36)) + list(range(37, 40))

filtered_df = data.iloc[indices_to_keep]

In [30]:
filtered_df.iloc[:, 0] = filtered_df.iloc[:, 0].str.strip()

for column in filtered_df.columns[1:]:
    if filtered_df[column].dtype == 'object': 
        filtered_df[column] = filtered_df[column].str.replace(',', '')

filtered_df = filtered_df.drop(31)
filtered_df

/var/folders/fd/3bl_2gw53px8fzkn9hzfjt8c0000gn/T/ipykernel_69528/3531067179.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df[column] = filtered_df[column].str.replace(',', '')

,Background group,2005,2005.1,2011,2011.1,2016,2011.2,2022,2022.1
4,Polish,1046000,0.01281,1424000,0.01795,1868000,0.02294,2201000,0.02649
5,Romanian,406000,0.00497,472000,0.00595,788000,0.00968,1096000,0.01319
6,Italian,794000,0.00973,701000,0.00883,861000,0.01057,905000,0.01089
7,Greek,386000,0.00473,349000,0.00440,443000,0.00544,434000,0.00522
8,Croat,410000,0.00502,325000,0.00410,441000,0.00542,419000,0.00504
9,Austrian,309000,0.00378,254000,0.00320,280000,0.00344,353000,0.00425
10,Bulgarian,49000,0.00060,77000,0.00097,238000,0.00292,340000,0.00409
11,Spanish,173000,0.00212,142000,0.00179,209000,0.00257,233000,0.00280
12,Dutch,190000,0.00233,203000,0.00256,206000,0.00253,233000,0.00280
13,French,157000,0.00192,153000,0.00193,168000,0.00206,228000,0.00274
16,Russian,1290000,0.01580,1189000,0.01498,1223000,0.01502,1354000,0.01629
17,Ukrainian,NaN,0.00000,246000,0.00310,272000,0.00334,583000,0.00702
18,Kosovar Albanian,NaN,0.00000,270000,0.00340,356000,0.00437,542000,0.00652
19,Bosnian,329000,0.00403,202000,0.00255,248000,0.00305,538000,0.00647
20,Serb,263065,0.00322,252000,0.00318,288000,0.00354,382000,0.00460
23,Turkish,2766000,0.03388,2643000,0.03331,2797000,0.03435,2835000,0.03411
24,Kazakh,NaN,0.00000,917000,0.01156,969000,0.01190,1325000,0.01594
25,Syrian,NaN,0.00000,53000,0.00067,521000,0.00640,1225000,0.01474
26,Afghan,88000,0.00108,131000,0.00165,231000,0.00284,435000,0.00523
27,Iraqi,113000,0.00138,106000,0.00134,206000,0.00253,393000,0.00473
28,Iranian,150000,0.00184,130000,0.00164,164000,0.00201,304000,0.00366
29,Chinese,80000,0.00098,93000,0.00117,157000,0.00193,217000,0.00261
30,Vietnamese,150000,0.00184,146000,0.00184,167000,0.00205,207000,0.00249
33,Sub-Saharan African,222000,0.00272,246000,0.00310,395000,0.00485,660000,0.00794
34,Moroccan,147000,0.00180,141000,0.00178,191000,0.00235,257000,0.00309
35,Other Maghreb countries:,108000,0.00132,121000,0.00152,158000,0.00194,242000,0.00291
37,American,140000,0.00171,123000,0.00155,154000,0.00189,216000,0.00260
38,Other peoples from the American continent,191000,0.00234,201000,0.00253,267000,0.00328,466000,0.00561
39,Australia/Oceania,NaN,0.00000,NaN,0.00000,40000,0.00049,26000,0.00031